### PR TITLE
Reorganize code

### PR DESCRIPTION
**Pull request by Jiefei-Wang**
Hi Martin,

Here is the update to the package. The major changes are:

1. Fix the frozen problem caused by the path, Redis port, or password issue in the worker script
2. Allow for user interrupt when waiting for the result from the worker
3. Define a `RedisBackend` reference class for wrapping the Redis functions. It is also the backend returned by `bpbackend`.
4. Move the code to different files to make them more readable and fits the package standard.
5. Add unit test to test the parallel functions if possible.

Some minor changes include:
1. `bpstart` will check whether the worker has been started before starting the worker.
2. Rename `bpstart_redis_worker_multicore()` to `.bpstart_redis_worker_in_background()` as the name `multicore` has another meaning in BiocParallel.

Please let me know your thought about it.

Best,
Jiefei

### CODE REVIEW

**Comment by mtmorgan** [comment]
Thanks; a trivial request is to reformat code so that for functions the opening `{` is left-justified and the first-level indentation is 4 characters rather than 8
```
{
    ...
```
Also, is there a reason for RedisManager to be a reference class, rather than an S3 class with standard functions implemented on it?

**Comment by Jiefei-Wang** [comment]
Thanks for the comment. For the indentation, do you mean the function like
```
RedisBackend <-
    function()
    {
        ...
     }
```
should be formatted as
```
RedisBackend <-
    function()
{
    ...
}
```
? I'm using the Rstudio code formatter, but I can try to find one that allows me to customize the format.



There are two reasons for making `RedisBackend` a reference class. 

1. `RedisBackend` serves as a connection to the Redis server. Any change in the server will be observable for `RedisBackend` objects with the same connection, so it behaves more like a reference object.

2. `RedisBackend` is a slot in `RedisParam` and contains a slot `redis_api` from `redux`. Since both `RedisParam` and `redis_api` are of the reference class, having `RedisBackend` as a reference class can make them consistent.


Either S3, S4 or reference classes should work, I can also convert it to a regular class. is there any preference in BiocParallel?

Best,
Jiefei

**Comment by mtmorgan** [comment]
The *Param classes are reference classes, but other classes are light-weight S3 classes, primarily used for dispatch and driven by use of S3 in the parallel package / snow backend. Did you see https://cran.r-project.org/web/packages/RcppRedis/index.html ?

**Comment by Jiefei-Wang** [comment]
Thanks for the info, I will make RedisBackend an S3 class. 

`RcppRedis` looks interesting. I think the main advantage of using it over `redux` is that there is no need to install the system package. I do not know how it works on Win but I can give it a shot.

Best,
Jiefei

**Comment by mtmorgan** [comment]
I'm not sure where we stand with this? I was hoping to go in logical steps but this seems to be sprawling a bit so difficult to associate the differences in the pull request to the original code, or to the rationale for why the changes are being made.

**Comment by Jiefei-Wang** [comment]
I originally wanted to make the function and variable names a little bit consistent and support the log system, I thought this should be a simple change but it looks like the job is more complicated than I thought, the log feature depends on `.send_all` and therefore reveals many bugs. Here is what I did in the recent commits:

1. Making `RedisBackend` an S3 class. 
2. Moving accessor functions to `RedisParam-accessors.R`
3. Adding log-related functions in the file `RedisParam-logger.R`
4. Fixing the bugs in `bpstart` and `bpstop`(and underlying `.send_all`). Local workers will be monitored and an error can be thrown if they are not started successfully.

The naming issue is not fixed yet, but I think I may move too fast, so I will stop here until we both agree the current changes can be merged. Please let me know if any changes need to be revised or revert.

Best,
Jiefei

**Comment by Jiefei-Wang** [comment]
Hi Martin, this is the final update for this pull request. It includes the changes we have made yesterday.

Best,
Jiefei

**Comment by mtmorgan** [comment]
I had started to clean up the pull request before your https://github.com/mtmorgan/RedisParam/pull/2/commits/e44ab206d8e0d31cbe3e0ebf44dcff5826ebb87f, so I did not include it (I think the missing whitespace cleanup was fixed anyway...)

I made three commits before merging the branch

- e5ee5de5f17e1ba6860716c37b72523b55afe07b is white space and other minor changes. The main files are RedisParam-class.R and RedisBackend-class.R; the material in AAA.R was moved to these files.
- 529bee87a73bcd7cf0cb56c4e14298393d56477a were changes mostly to make R CMD check pass without error / warning, plus some slightly more substantial changes to the code as summarized in the commit message
- 00320797a7bb144c8e39e4e2f14246dd08ca0e61 is probably the biggest change, with bpworker,RedisParam returning the _expected_ number of workers; the show method has a final field 'running workers' to show the actual number.

**Pull request closed without merging**
